### ISSUE TITLE
Adding events without start date creates action not allowed exceptions March 2025 and after

### ISSUE THREAD

**Issue by jmarmstrong1207** [saegl5/jiayou_add_events#4]
Using my new PR #3, there is a bug where it won't create the events after a certain date. This certain date changes depending on the jiayou days you select.

It sounds like a quota limit or something. Screenshot below happens when I selected all jiayou dates. I added a try catch block to get this to show up in logger.log

![Screenshot 2024-09-27 at 1 02 28 PM](https://github.com/user-attachments/assets/57f0d6b0-0430-4b43-97f8-5cabf8639ff4)

**Comment by saegl5** [comment]
hi @jmarmstrong1207 looking into this now

**Comment by saegl5** [comment]
@jmarmstrong1207 

Definitely seems like a use limit to me...

Dry run enabled: no issues

Dry run disabled: 87 events max
I tried three times with all letter days, different start dates (none or one), got the same limit of 87

For recurring events, 730 is supposed to be the limit: https://support.google.com/calendar/answer/37115?hl=en&co=GENIE.Platform%3DDesktop#:~:text=Tip%3A%20Repeating%20events%20in%20Google,a%20limit%20of%20730%20occurrences.

But the above link assumes you are creating recurring events in Google Calendar, which only uses RRULE.
We are using RDATE...

By the way, for some use limits users must wait to retry actions.
Contrast the above link's info about use limits for creating recurring events with [this one](https://support.google.com/a/answer/2905486)'s about use limits for other actions.

**Comment by saegl5** [comment]
The Web app for [creating the calendar](https://github.com/saegl5/jiayou_create_calendar) adds ~~individual events.~~ **recurring events now.**
This Web app adds recurring events.

Makes sense that we see a different outcome (different limit for different approaches), unfortunately I don't see a workaround other than adding individual events to letter days (not ideal!)

On the bright side, from personal experience, no one has ever needed to add recurring events to more than one letter day... of course that doesn't mean no one will, but... we are probably okay
...and being able to add recurring events to multiple letter days is a nice addition

**Comment by saegl5** [comment]
mitigated in a64490469952c8db175529f8bc058299d3f6395b (add events as separate recurring series)

**Comment by saegl5** [comment]
@jmarmstrong1207 
btw, I re-tested (add on all letter days) with my latest commit and encountered no exceptions
